#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-FDPass
Version  : 1.3
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/IO-FDPass-1.3.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/IO-FDPass-1.3.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-IO-FDPass-license = %{version}-%{release}
Requires: perl-IO-FDPass-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Canary::Stability)

%description
NAME
IO::FDPass - pass a file descriptor over a socket
SYNOPSIS
use IO::FDPass;
IO::FDPass::send fileno $socket, fileno $fh_to_pass
or die "send failed: $!";

%package dev
Summary: dev components for the perl-IO-FDPass package.
Group: Development
Provides: perl-IO-FDPass-devel = %{version}-%{release}
Requires: perl-IO-FDPass = %{version}-%{release}

%description dev
dev components for the perl-IO-FDPass package.


%package license
Summary: license components for the perl-IO-FDPass package.
Group: Default

%description license
license components for the perl-IO-FDPass package.


%package perl
Summary: perl components for the perl-IO-FDPass package.
Group: Default
Requires: perl-IO-FDPass = %{version}-%{release}

%description perl
perl components for the perl-IO-FDPass package.


%prep
%setup -q -n IO-FDPass-1.3
cd %{_builddir}/IO-FDPass-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-IO-FDPass
cp %{_builddir}/IO-FDPass-%{version}/COPYING %{buildroot}/usr/share/package-licenses/perl-IO-FDPass/9a56f3b919dfc8fced3803e165a2e38de62646e5
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/IO::FDPass.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-IO-FDPass/9a56f3b919dfc8fced3803e165a2e38de62646e5

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
